import { useLayoutEffect, useMemo, useRef, useState, type InputHTMLAttributes } from 'react';
import type { Deck } from '../../contracts/models';
import { MAX_DESCRIPTION_LENGTH, MAX_LINKS_COUNT, MAX_TITLE_LENGTH } from '../../contracts/limits';
import type { EditorContent, EditorService } from './types';
import { useEditor } from './useEditor';
import { CoverPreview } from './CoverPreview';

const directoryAttributes = { webkitdirectory: '', directory: '' } as InputHTMLAttributes<HTMLInputElement>;
export function EditorForm({ deck, service, content, onClose, onComplete }: { deck?: Deck; service: EditorService; content: EditorContent; onClose?: () => void; onComplete?: (deck: Deck) => void }) {
  const editor = useEditor({ deck, service, content, onComplete });
  const summary = useRef<HTMLDivElement>(null);
  const [focusSummary, setFocusSummary] = useState(0);
  const [dragging, setDragging] = useState(false);
  useLayoutEffect(() => { if (focusSummary) summary.current?.focus(); }, [focusSummary]);
  const originalCover = useMemo(() => deck ? { bytes: deck.cover, source: deck.coverSource, mimeType: deck.cover[0] === 0xff ? 'image/jpeg' as const : 'image/webp' as const } : undefined, [deck]);
  const displayedCover = editor.cover ?? originalCover;
  const disabled = !!editor.phase || editor.saved;
  function error(key: string) { return editor.errors[key] && <p id={`editor-${key}-error`} className="editor-error">{editor.errors[key]}</p>; }
  function attributes(key: string) { return { id: `editor-${key}`, 'aria-invalid': !!editor.errors[key], 'aria-describedby': editor.errors[key] ? `editor-${key}-error` : undefined, onBlur: () => editor.validateField(key) }; }
  const fileName = editor.prepared?.fileName ?? deck?.fileName;
  const kind = editor.prepared?.kind ?? deck?.kind;
  return <section className="vektor-editor" aria-label="Sunum düzenleyici">
    <header className="editor-header"><div><p className="editor-eyebrow">VEKTÖR / SUNUM</p><h1>{deck ? 'Sunumu Düzenle' : 'Yeni Sunum Yükle'}</h1><p>{deck ? 'Bilgileri güncelleyin veya aynı biçimde bir dosya seçin.' : 'HTML veya PowerPoint sunumunuzu ekibinizle paylaşın.'}</p></div><button className="btn btn-secondary" type="button" onClick={onClose}>Geri dön</button></header>
    <div className="editor-review"><strong>{deck ? 'Değişiklikler yeniden incelemeye gönderilir.' : 'Sunumunuz yönetici onayından sonra yayınlanır.'}</strong><p>{deck?.status === 'pending' ? 'Bu sunum zaten onay bekliyor; düzenleme yeni bekleyen sunum kotası kullanmaz.' : 'En fazla 5 sunum onay bekleyebilir. Bu gönderim yeni bir bekleyen sunum kotası kullanır.'}</p>{deck?.status === 'rejected' && deck.rejectNote && <p>Ret notu: {deck.rejectNote}</p>}</div>
    <form noValidate onSubmit={event => { event.preventDefault(); void editor.submit().then(result => { if (result === 'invalid') setFocusSummary(value => value + 1); }); }}>
      {focusSummary > 0 && Object.keys(editor.errors).length > 0 && <div ref={summary} tabIndex={-1} role="alert" className="editor-summary"><h2>Bilgileri kontrol edin</h2><ul>{Object.entries(editor.errors).map(([key, value]) => <li key={key}><a href={`#editor-${key}`} onClick={event => { event.preventDefault(); document.getElementById(`editor-${key}`)?.focus(); }}>{value}</a></li>)}</ul></div>}
      <div className="editor-columns"><div className="editor-main">
        <section className="editor-section"><h2>Sunum bilgileri</h2><div className="form-group"><label className="form-label" htmlFor="editor-title">Sunum başlığı (zorunlu)</label><input className="form-input" {...attributes('title')} value={editor.title} onChange={event => { editor.clearError('title'); editor.changeTitle(event.target.value); }} disabled={disabled} required /><div className="editor-hint">En fazla {MAX_TITLE_LENGTH} karakter · {editor.title.length}/{MAX_TITLE_LENGTH}</div>{error('title')}</div>
          <div className="form-group"><label className="form-label" htmlFor="editor-description">Açıklama</label><textarea className="form-textarea" {...attributes('description')} value={editor.description} onChange={event => { editor.clearError('description'); editor.setDescription(event.target.value); }} disabled={disabled} rows={5} /><div className="editor-hint">En fazla {MAX_DESCRIPTION_LENGTH} karakter · {editor.description.length}/{MAX_DESCRIPTION_LENGTH}</div>{error('description')}</div>
        </section>
        <section className="editor-section"><div className="editor-section-heading"><h2>Kaynak bağlantıları</h2><span className="editor-hint">{editor.links.length}/{MAX_LINKS_COUNT}</span></div><p className="editor-hint">İsteğe bağlı. Tam HTTPS adresleri kullanın; kullanıcı adı veya parola eklemeyin.</p>
          {editor.links.map((link, index) => <div className="editor-link" key={index}><div className="form-group"><label className="form-label" htmlFor={`editor-link-${index}-label`}>Bağlantı {index + 1} etiketi</label><input className="form-input" {...attributes(`link-${index}-label`)} value={link.label} disabled={disabled} onChange={event => { editor.clearError(`link-${index}-label`); editor.setLinks(editor.links.map((item, i) => i === index ? { ...item, label: event.target.value } : item)); }} />{error(`link-${index}-label`)}</div><div className="form-group"><label className="form-label" htmlFor={`editor-link-${index}-url`}>Bağlantı {index + 1} HTTPS adresi</label><input type="url" className="form-input" {...attributes(`link-${index}-url`)} value={link.url} disabled={disabled} onChange={event => { editor.clearError(`link-${index}-url`); editor.setLinks(editor.links.map((item, i) => i === index ? { ...item, url: event.target.value } : item)); }} />{error(`link-${index}-url`)}</div><button type="button" className="btn btn-secondary" disabled={disabled} onClick={() => editor.setLinks(editor.links.filter((_, i) => i !== index))} aria-label={`Bağlantı ${index + 1} kaldır`}>Kaldır</button></div>)}
          {error('links')}<button className="btn btn-secondary" type="button" id="editor-links" disabled={disabled || editor.links.length >= MAX_LINKS_COUNT} onClick={() => editor.setLinks([...editor.links, { label: '', url: '' }])}>Bağlantı ekle</button>
        </section>
        <section className="editor-section"><h2>{deck ? 'Sunum dosyasını değiştir' : 'Sunum dosyası'}</h2>
          {fileName && <div className="editor-file-info"><strong>{fileName}</strong><span>{kind === 'pptx' ? 'PPTX' : 'HTML'} · {editor.prepared ? 'Yeni içerik hazır' : 'Mevcut içerik korunur'}</span></div>}
          <div className={`editor-dropzone${dragging ? ' editor-dragging' : ''}`} onDragOver={event => { event.preventDefault(); if (!disabled) setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={event => { event.preventDefault(); setDragging(false); if (!disabled) void editor.selectFiles(Array.from(event.dataTransfer.files)); }}>
            <svg aria-hidden="true" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M12 16V3m-5 5 5-5 5 5M3 15v6h18v-6" /></svg><p><strong>Dosyanızı buraya sürükleyin</strong></p><p className="editor-hint">veya aşağıdaki seçim alanlarını kullanın</p>
            <div className="editor-pickers"><div><label htmlFor="editor-file" className="form-label">HTML, ZIP veya PPTX seç</label><input id="editor-file" type="file" accept={deck?.kind === 'pptx' ? '.pptx' : deck?.kind === 'html' ? '.html,.htm,.zip' : '.html,.htm,.zip,.pptx'} disabled={disabled} aria-describedby="editor-file-hint" onChange={event => { const files = Array.from(event.target.files ?? []); event.target.value = ''; if (files.length) void editor.selectFiles(files); }} /></div>{deck?.kind !== 'pptx' && <div><label htmlFor="editor-directory" className="form-label">HTML klasörü seç</label><input {...directoryAttributes} id="editor-directory" type="file" multiple disabled={disabled} aria-describedby="editor-file-hint" onChange={event => { const files = Array.from(event.target.files ?? []); event.target.value = ''; if (files.length) void editor.selectFiles(files, true); }} /></div>}</div>
          </div><p id="editor-file-hint" className="editor-hint">HTML: en fazla 300 dosya, 25 MB açılmış, 5 MB sıkıştırılmış. ZIP dosyası en fazla 25 MB. PPTX: en fazla 8 MB. Dosya değişimi mevcut sunumun biçimini korur.</p>{error('file')}
          {editor.selected && editor.selected.candidates.length > 1 && <div className="form-group"><label className="form-label" htmlFor="editor-entry">HTML giriş dosyası (zorunlu)</label><select className="form-select" id="editor-entry" disabled={disabled} value={editor.selected.entry} onChange={event => void editor.chooseEntry(event.target.value)}><option value="">Giriş dosyasını seçin</option>{editor.selected.candidates.map(path => <option key={path} value={path}>{path}</option>)}</select></div>}
          {editor.fileError && <div role="alert" className="editor-error"><p>{editor.fileError}</p><button type="button" className="btn btn-secondary" disabled={disabled} onClick={() => void editor.retryFile()}>Hazırlamayı yeniden dene</button></div>}
          {deck && <button type="button" className="btn btn-secondary" disabled={disabled} onClick={editor.clearReplacement}>Mevcut içeriği koru</button>}
          {editor.prepared && <div className="editor-ready"><strong>Sunum hazır</strong><p>{editor.prepared.sizes.fileCount} dosya · {(editor.prepared.sizes.encoded / 1024 / 1024).toLocaleString('tr-TR', { maximumFractionDigits: 2 })} MB</p></div>}
          {!!editor.prepared?.warnings.length && <div className="editor-warnings" role="status"><h3>Hazırlama uyarıları</h3><ul>{editor.prepared.warnings.map((warning, index) => <li key={index}>{warning.message}{warning.target && <span> — {warning.target}</span>}</li>)}</ul></div>}
          {(editor.prepared || deck) && <button type="button" className="btn btn-secondary" disabled={disabled} onClick={() => void editor.openPreview()}>Sunumu önizle</button>}
          {editor.previewError && <div role="alert" className="editor-error"><p>{editor.previewError}</p><button type="button" className="btn btn-secondary" disabled={disabled} onClick={() => void editor.openPreview()}>Önizlemeyi yeniden dene</button></div>}
        </section>
      </div><aside className="editor-side"><section className="editor-section"><h2>Kapak görseli</h2><CoverPreview cover={displayedCover} title={editor.title} /><p className="editor-hint">{displayedCover?.source === 'upload' ? 'Yüklediğiniz kapak' : displayedCover?.source === 'auto' ? 'Sunumdan otomatik yakalanan kapak' : displayedCover ? 'Varsayılan kapak' : 'Otomatik veya varsayılan kapak hazırlanır.'}</p><div className="form-group"><label className="form-label" htmlFor="editor-cover-file">Kapak yükle veya değiştir</label><input id="editor-cover-file" type="file" accept="image/jpeg,image/png,image/webp" disabled={disabled} onChange={event => { const file = event.target.files?.[0]; event.target.value = ''; if (file) void editor.chooseCover(file); }} /><p className="editor-hint">JPEG, PNG veya WebP · kaynak en fazla 10 MB, 8192 px ve 16 MP. Kapak 640 × 360 boyutuna işlenir.</p></div>{editor.coverError && <p role="alert" className="editor-error">{editor.coverError}</p>}<div className="editor-cover-actions"><button className="btn btn-secondary" type="button" disabled={disabled} onClick={() => void editor.resetCover('default')}>Varsayılan kapağa dön</button>{editor.prepared?.autoCover && <button className="btn btn-secondary" type="button" disabled={disabled} onClick={() => void editor.resetCover('auto')}>Otomatik kapağı kullan</button>}{deck && <button className="btn btn-secondary" type="button" disabled={disabled} onClick={() => void editor.resetCover('original')}>Mevcut kapağı koru</button>}</div></section></aside></div>
      {editor.preview && <section className="editor-preview" aria-label="Sunum önizlemesi"><div className="editor-section-heading"><h2>Sunum önizlemesi</h2><button type="button" className="btn btn-secondary" onClick={editor.closePreview}>Önizlemeyi kapat</button></div>{editor.preview.kind === 'html' ? <iframe sandbox="allow-scripts" allow="fullscreen" title={`${editor.title || 'Sunum'} — önizleme`} srcDoc={editor.preview.html} /> : <div className="editor-pptx"><h3>{fileName}</h3><p>PPTX sunumu dosya olarak saklanır.</p><p>Bu dosya antivirüs taramasından geçirilmemiştir. Açmadan önce güvenlik yazılımınızla tarayın.</p></div>}</section>}
      {editor.phase && <div className="editor-progress" role="status"><progress aria-label={editor.phase} /><p>{editor.phase}</p></div>}{editor.message && <p className={editor.saved ? 'editor-ready' : 'editor-error'} role={editor.saved ? 'status' : 'alert'}>{editor.message}</p>}
      <footer className="editor-footer"><button type="button" className="btn btn-secondary" onClick={onClose}>Vazgeç</button><button type="submit" className="btn btn-primary" disabled={disabled}>{editor.saved ? 'Onaya gönderildi' : editor.phase ? 'İşleniyor…' : deck ? 'Değişiklikleri onaya gönder' : 'Onaya gönder'}</button></footer>
    </form>
  </section>;
}
