import { afterAll, afterEach, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import { chromium, expect as check, type Browser, type BrowserContext, type Page } from '@playwright/test';
import { createServer, type ViteDevServer } from 'vite';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { zipSync, strToU8 } from 'fflate';
import { smallHtml, raster, pptx, zip } from './fixture-bytes';
import type { EditorHarness } from './harness';
import type { metrics as fixtureMetrics, flags as fixtureFlags } from './fixtures';
const evidence = join(process.env.EVIDENCE_DIR || 'test-results/unit', `run-${new Date().toISOString().replace(/[:.]/g, '-')}`);
let server: ViteDevServer, browser: Browser, context: BrowserContext, page: Page, base: string;
const reports: object[] = [], shots: string[] = [];
let errors: string[];
const file = () => page.locator('#editor-file');
const submit = () => page.locator('.editor-footer button[type="submit"]');
async function metrics() { return page.evaluate(() => window.editorMetrics); }
async function flags(value: Partial<typeof fixtureFlags>) { await page.evaluate(value => window.editor.flags(value), value); }
async function control(method: keyof EditorHarness, value?: unknown) { await page.evaluate(({ method, value }) => { Reflect.apply(window.editor[method], window.editor, value === undefined ? [] : [value]); }, { method, value }); }
async function enterEdit(id = 'own') { await control('auth', 'member'); await control('edit', id); await check(page.getByRole('heading', { name: 'Sunumu Düzenle', exact: true })).toBeVisible(); }
async function enterCreate() { await control('auth', 'member'); await control('create'); await check(page.getByRole('heading', { name: 'Yeni Sunum Yükle', exact: true })).toBeVisible(); }
async function prepare(name = 'test.html', bytes = Buffer.from(smallHtml), mimeType = 'text/html') { await file().setInputFiles({ name, mimeType, buffer: bytes }); await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); await check(submit()).toBeEnabled(); }
async function send() { await submit().click(); await check(page.getByText('Sunum onaya gönderildi.', { exact: true })).toBeVisible(); }
function report(name: string, data?: unknown) { reports.push({ acceptance: name, passed: true, data }); }
async function shot(name: string) { const preview = name.startsWith('html-preview'); if (preview) { await page.locator('.editor-preview').scrollIntoViewIfNeeded(); await check(page.frameLocator('.editor-preview iframe').getByRole('heading', { name: 'Test Sunumu', exact: true })).toBeVisible(); } else await page.evaluate(() => window.scrollTo({ top: 0, behavior: 'instant' })); const path = join(evidence, `${name}.png`); await page.screenshot({ path, fullPage: !preview }); shots.push(path); }
beforeAll(async () => {
  mkdirSync(evidence, { recursive: true });
  console.info(`Editor runtime evidence: ${evidence}`);
  try {
    server = await createServer({ root: process.cwd(), server: { host: '127.0.0.1', port: 0 }, logLevel: 'error' }); await server.listen();
    const address = server.httpServer!.address(); if (!address || typeof address === 'string') throw new Error('No ephemeral server'); base = `http://127.0.0.1:${address.port}`;
    browser = await chromium.launch({ headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'] });
  } catch (error) { if (server) await server.close(); throw error; }
}, 30_000);
beforeEach(async () => {
  errors = []; context = await browser.newContext({ viewport: { width: 1280, height: 900 }, colorScheme: 'dark', reducedMotion: 'reduce' });
  page = await context.newPage(); page.setDefaultTimeout(10_000); page.on('pageerror', error => errors.push(error.message));
  await page.goto(`${base}/tests/editor/harness.html`); await check(page.getByRole('heading', { name: 'Sunum yüklemek için giriş yapın.' })).toBeVisible();
}, 20_000);
afterEach(async () => { try { expect(errors).toEqual([]); } finally { if (context) await context.close(); } }, 20_000);
afterAll(async () => {
  writeFileSync(join(evidence, 'browser-assertions.json'), JSON.stringify({ browser: 'real Playwright Chromium', reports, screenshots: shots }, null, 2));
  try { if (browser) await browser.close(); } finally { if (server) await server.close(); }
}, 20_000);
describe('actual upload and owner editor in Chromium', { timeout: 180_000 }, () => {
  it('gates loading visitors unverified invalid ID and foreign ownership including admin with zero chunks and mutations', async () => {
    for (const role of ['loading', 'unauthenticated', 'unverified']) { await control('auth', role); await control('edit', 'own'); expect((await metrics()).reads).toEqual([]); expect((await metrics()).prep).toBe(0); expect((await metrics()).mutations).toEqual([]); await check(file()).toHaveCount(0); }
    await control('edit', '../bad'); await control('auth', 'member'); await check(page.getByRole('alert')).toContainText('kimliği'); expect((await metrics()).reads).toEqual([]);
    await flags({ foreign: true }); await control('edit', 'foreign'); await check(page.getByRole('alert')).toContainText('kendi sunumunuzu'); await control('auth', 'admin'); await check(page.getByRole('alert')).toContainText('kendi sunumunuzu'); expect((await metrics()).chunks).toEqual([]); expect((await metrics()).mutations).toEqual([]); await check(page.getByRole('main')).toHaveCount(1); report('member gates valid ID foreign owner admin denial zero processing/chunks/writes', await metrics());
  });
  it('loads metadata lazily with missing permission transport throw retry and bounds before chunks', async () => {
    await control('auth', 'member'); for (const id of ['missing', 'permission']) { await control('edit', id); await check(page.getByRole('alert')).toBeVisible(); await check(file()).toHaveCount(0); }
    await flags({ error: 'read' }); await control('edit', 'own'); await check(page.getByRole('alert')).toContainText('yüklenemedi'); await flags({ error: '' }); await page.getByRole('button', { name: 'Yeniden dene', exact: true }).click(); await check(page.locator('#editor-title')).toHaveValue('Mevcut Sunum'); expect((await metrics()).chunks).toEqual([]);
    await flags({ throws: 'read' }); await control('service'); await check(page.getByRole('alert')).toContainText('yüklenemedi'); await flags({ throws: '', malformed: true }); await page.getByRole('button', { name: 'Yeniden dene', exact: true }).click(); await check(page.locator('#editor-title')).toBeVisible(); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); await check(page.getByRole('alert')).toContainText('manifesti'); expect((await metrics()).chunks).toEqual([]); report('get error/notfound/permission/throw retry lazy metadata invalid bounds before chunks', await metrics());
  });
  it('creates all four design fixtures and ZIP with real automatic covers, reconstructs helper-free stored HTML then rejects sixth and recovers PPTX', async () => {
    await enterCreate();
    for (const fixture of ['flutter-fluid-rendering', 'local-first-crdt-sync', 'multi-agent-orchestration', 'zero-dependency-design-tokens']) {
      await file().setInputFiles(join(process.cwd(), 'design/presentations', `${fixture}.html`)); await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 });
      await check(page.locator('.editor-cover img')).toBeVisible(); await send(); const m = (await metrics()).mutations.at(-1)!;
      expect(m.kind).toBe('html'); expect(m.html).toContain('<html'); expect(m.helper).toBe(false); expect(m.coverBytes).toBeGreaterThan(0); expect(m.coverSource).toBe('auto'); expect(m.keys).toEqual(['category', 'chunkCount', 'chunks', 'cover', 'coverSource', 'description', 'fileName', 'kind', 'links', 'manifest', 'sizes', 'tags', 'title']);
      const identity = await page.evaluate(() => { const input = window.editorInputs.at(-1)!; if (!('kind' in input)) return false; const rebuilt = window.editorContent.reconstructPresentation(input.chunks, input.manifest, input.kind, input.sizes); const bytes = window.editorContent.prepareChunks(rebuilt.ok ? rebuilt.value.rawBytes : new Uint8Array(), input.kind); const stored = input.chunks.flatMap(chunk => Array.from(chunk.data)); return bytes.ok && bytes.value.encodedData.length === stored.length && bytes.value.encodedData.every((byte, i) => byte === stored[i]); }); expect(identity).toBe(true);
      await control('create');
    }
    await prepare('slides.zip', zip, 'application/zip'); await send(); expect((await metrics()).mutations.at(-1)?.coverSource).toBe('auto'); await control('create');
    await prepare('safe.pptx', pptx, 'application/vnd.openxmlformats-officedocument.presentationml.presentation'); await submit().click(); await check(page.getByRole('alert')).toContainText('En fazla 5'); expect((await metrics()).completions).toHaveLength(5); await flags({ pending: 4 }); await send(); const m = (await metrics()).mutations.at(-1)!; expect(m.kind).toBe('pptx'); expect(m.coverSource).toBe('default'); expect(m.html).toBeUndefined(); report('all 4 design fixture actual prepare/auto cover/create/identity/helper-free plus ZIP fifth PPTX sixth quota recovery', await metrics());
  });
  it('uses real directory relative paths and requires explicit entry selection/change without overwriting typed metadata', async () => {
    await enterCreate(); await page.locator('#editor-title').fill('Benim başlığım'); await page.locator('#editor-description').fill('Açıklamam');
    await page.locator('#editor-directory').setInputFiles(join(process.cwd(), 'tests/editor/fixtures/bundle')); await check(page.locator('#editor-entry')).toBeVisible(); expect((await metrics()).prep).toBe(0); await submit().click(); await check(page.locator('.editor-summary')).toBeFocused(); expect((await metrics()).mutations).toEqual([]);
    await page.locator('#editor-entry').selectOption('index.html'); await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); await page.locator('#editor-entry').selectOption('second.html'); await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); await check(page.locator('#editor-title')).toHaveValue('Benim başlığım'); await check(page.locator('#editor-description')).toHaveValue('Açıklamam'); await send(); expect((await metrics()).mutations.at(-1)?.html).toContain('İkinci giriş'); expect((await metrics()).mutations.at(-1)?.coverSource).toBe('auto'); report('actual webkitdirectory relative paths ambiguity choice change preserves metadata real auto cover', await metrics());
  });
  it('preserves nested raw directory paths so explicit second HTML entry reaches the pipeline without double root stripping', async () => {
    await enterCreate(); await page.locator('#editor-directory').setInputFiles(join(process.cwd(), 'tests/editor/fixtures/nested')); await check(page.locator('#editor-entry')).toBeVisible(); await check(page.locator('#editor-entry option[value="slides/second.html"]')).toHaveCount(1); await page.locator('#editor-entry').selectOption('slides/second.html'); await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); await check(page.locator('#editor-title')).toHaveValue('İkinci iç içe giriş'); await send(); const mutation = (await metrics()).mutations.at(-1)!; expect(mutation.html).toContain('İkinci iç içe giriş'); expect(mutation.html).not.toContain('Birinci iç içe giriş'); report('real nested webkitdirectory raw path preservation and explicit second entry reaches actual frozen pipeline', await metrics());
  });
  it('prepares with real drag/drop and preview enforces exact opaque sandbox and parent separation, close and cover URL cleanup', async () => {
    await enterCreate(); await page.getByRole('tab', { name: 'Tek HTML', exact: true }).click();
    await page.locator('.editor-dropzone').evaluate((element, html) => { const dataTransfer = new DataTransfer(); dataTransfer.items.add(new File([html], 'dropped.html', { type: 'text/html' })); element.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer })); }, smallHtml);
    await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); const frame = page.locator('.editor-preview iframe'); await check(frame).toHaveAttribute('sandbox', 'allow-scripts'); await check(frame).toHaveAttribute('allow', 'fullscreen'); await check(frame).toHaveAttribute('title', 'Test Sunumu — önizleme'); await check(page.frameLocator('.editor-preview iframe').locator('body')).toHaveAttribute('data-isolated', 'yes'); await check(page.locator('#deck-only')).toHaveCount(0); expect(await page.locator('body').getAttribute('data-escaped')).toBeNull(); expect(await frame.getAttribute('srcdoc')).not.toContain('VEKTOR_COVER_CAPTURE');
    await page.getByRole('button', { name: 'Önizlemeyi kapat' }).click(); await check(page.locator('.editor-preview')).toHaveCount(0); await control('mount', false); const m = await metrics(); expect(m.urls.every(url => m.revoked.includes(url))).toBe(true); report('real drag/drop opaque prepared iframe parent denial no parent markup/helper close URL unmount cleanup', m);
  });
  it('lazy original HTML preview handles chunk failure throw retry and PPTX contains warning without iframe/chunks', async () => {
    await enterEdit(); expect((await metrics()).chunks).toEqual([]); await flags({ error: 'chunks' }); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); await check(page.getByRole('alert')).toContainText('İçerik okunamadı'); await flags({ error: '', throws: 'chunks' }); await page.getByRole('button', { name: 'Önizlemeyi yeniden dene' }).click(); await check(page.getByRole('alert')).toContainText('Önizleme yüklenemedi'); await flags({ throws: '' }); await page.getByRole('button', { name: 'Önizlemeyi yeniden dene' }).click(); await check(page.frameLocator('.editor-preview iframe').locator('#original-title')).toHaveText('Mevcut içerik');
    await control('edit', 'pptx'); await check(page.locator('#editor-title')).toBeVisible(); const before = (await metrics()).chunks.length; await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); await check(page.locator('.editor-pptx')).toContainText('antivirüs'); await check(page.locator('iframe')).toHaveCount(0); expect((await metrics()).chunks).toHaveLength(before); report('explicit original preview only chunk error/throw/retry actual reconstruct PPTX warning no converter/frame', await metrics());
  });
  it('keeps plain HTML readable on the native white iframe fallback and preserves authored deck backgrounds', async () => {
    const styles = [];
    for (const authored of [false, true]) {
      await enterCreate();
      const html = `<!doctype html><html><head><title>Readable preview</title>${authored ? '<style>body{background:#123456;color:#ffffff}</style>' : ''}</head><body><h1>Readable preview</h1></body></html>`;
      await prepare('readable.html', Buffer.from(html)); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click();
      const frame = page.locator('.editor-preview iframe'); await frame.scrollIntoViewIfNeeded();
      const heading = page.frameLocator('.editor-preview iframe').getByRole('heading', { name: 'Readable preview', exact: true }); await check(heading).toBeVisible();
      const computed = await heading.evaluate(element => ({ color: getComputedStyle(element).color, body: getComputedStyle(document.body).backgroundColor, html: getComputedStyle(document.documentElement).backgroundColor }));
      const fallback = await frame.evaluate(element => getComputedStyle(element).backgroundColor);
      expect(fallback).toBe('rgb(255, 255, 255)'); expect(computed.html).toBe('rgba(0, 0, 0, 0)');
      expect(computed.color).toBe(authored ? 'rgb(255, 255, 255)' : 'rgb(0, 0, 0)'); expect(computed.body).toBe(authored ? 'rgb(18, 52, 86)' : 'rgba(0, 0, 0, 0)');
      const luminance = (rgb: number[]) => rgb.map(value => value / 255).map(value => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4).reduce((total, value, i) => total + value * [.2126, .7152, .0722][i], 0);
      const contrast = authored ? 1.05 / (luminance([18, 52, 86]) + .05) : 21; expect(contrast).toBeGreaterThanOrEqual(4.5);
      const rect = await heading.boundingBox(); expect(rect).not.toBeNull(); expect(rect!.y).toBeGreaterThanOrEqual(0); expect(rect!.y + rect!.height).toBeLessThanOrEqual(900);
      const srcdoc = await frame.getAttribute('srcdoc'); expect(srcdoc).toContain('<h1>Readable preview</h1>'); expect(srcdoc).not.toContain('VEKTOR_COVER_CAPTURE'); if (authored) expect(srcdoc).toContain('body{background:#123456;color:#ffffff}'); else expect(srcdoc).not.toContain('<style');
      const screenshot = join(evidence, `readable-preview-${authored ? 'authored' : 'plain'}.png`); await page.screenshot({ path: screenshot }); styles.push({ authored, computed, fallback, contrast, screenshot });
    }
    report('actual plain HTML black text transparent child surfaces readable white iframe fallback contrast21; authored dark body and white text preserved', styles);
  });
  it('handles preparation cover and capture errors with visible warnings preserving selected cover and recovery', async () => {
    await enterCreate(); await flags({ error: 'prep' }); await file().setInputFiles({ name: 'test.html', mimeType: 'text/html', buffer: Buffer.from(smallHtml) }); await check(page.getByRole('alert')).toContainText('Sunum hazırlanamadı'); await flags({ error: '', throws: 'prep' }); await page.getByRole('button', { name: 'Hazırlamayı yeniden dene' }).click(); await check(page.getByRole('alert')).toContainText('Sunum hazırlanamadı'); await flags({ throws: '', captureFailure: true }); await page.getByRole('button', { name: 'Hazırlamayı yeniden dene' }).click(); await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); await check(page.locator('.editor-warnings')).toContainText('Otomatik kapak');
    const initial = await page.locator('.editor-cover img').getAttribute('src'); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByText('Yüklediğiniz kapak', { exact: true })).toBeVisible(); expect(await page.locator('.editor-cover img').getAttribute('src')).not.toBe(initial); const uploaded = await page.locator('.editor-cover img').getAttribute('src');
    await page.locator('#editor-cover-file').setInputFiles({ name: 'invalid.svg', mimeType: 'image/svg+xml', buffer: Buffer.from('<svg/>') }); await check(page.getByRole('alert')).toBeVisible(); expect(await page.locator('.editor-cover img').getAttribute('src')).toBe(uploaded); await flags({ error: 'cover' }); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByRole('alert')).toContainText('Kapak işlenemedi'); await flags({ error: '', throws: 'cover' }); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByRole('alert')).toContainText('Kapak işlenemedi'); await flags({ throws: '' }); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByText('Yüklediğiniz kapak', { exact: true })).toBeVisible();
    await page.getByRole('button', { name: 'Varsayılan kapağa dön' }).click(); await check(page.getByText('Varsayılan kapak', { exact: true })).toBeVisible(); await send(); expect((await metrics()).mutations.at(-1)?.coverSource).toBe('default'); report('real raster process/resize override invalid preserve reset capture deadline fallback warnings prep/cover retry', await metrics());
  });
  it('rejects formats traversal duplicate paths count byte PPTX and malformed prepared bounds with zero writes; restores invalid edit replacement explicitly', async () => {
    await enterCreate();
    for (const [name, buffer] of [['bad.txt', Buffer.from('text')], ['bad.pptx', Buffer.from('PKinvalid')], ['traversal.zip', Buffer.from(zipSync({ '../outside.html': strToU8(smallHtml) }))], ['missing.zip', Buffer.from(zipSync({ 'asset.css': strToU8('body{}') }))]] as const) { await file().setInputFiles({ name, buffer, mimeType: 'application/octet-stream' }); await check(page.locator('.editor-section [role="alert"]')).toBeVisible(); await submit().click(); expect((await metrics()).mutations).toEqual([]); }
    const guard = await page.evaluate(async () => {
      const outcomes: string[] = [];
      for (const scenario of ['count', 'unpacked', 'pptx', 'duplicate', 'path']) {
        let files = [new File(['html'], 'index.html')]; let reads = 0;
        if (scenario === 'count') files = Array.from({ length: 301 }, (_, i) => new File([''], `${i}.html`));
        if (scenario === 'unpacked') Object.defineProperty(files[0], 'size', { value: 26 * 1024 * 1024 });
        if (scenario === 'pptx') { files = [new File([''], 'big.pptx')]; Object.defineProperty(files[0], 'size', { value: 9 * 1024 * 1024 }); }
        if (scenario === 'duplicate') files = [new File([''], 'INDEX.html'), new File([''], 'index.html')];
        if (scenario === 'path') files = [new File([''], '../index.html')];
        files.forEach(file => { file.arrayBuffer = async () => { reads++; return new ArrayBuffer(0); }; });
        try { await window.readEditorFiles(files, scenario === 'count' || scenario === 'duplicate', () => true); outcomes.push('unexpected pass'); } catch { outcomes.push(`${scenario}:${reads}`); }
      }
      return outcomes;
    }); expect(guard).toEqual(['count:0', 'unpacked:0', 'pptx:0', 'duplicate:0', 'path:0']);
    for (const badPrepared of ['encoded', 'files', 'manifest']) { await control('create'); await flags({ badPrepared }); await file().setInputFiles({ name: 'test.html', mimeType: 'text/html', buffer: Buffer.from(smallHtml) }); if (badPrepared === 'manifest') await check(page.getByText('Sunum hazır', { exact: true })).toBeVisible({ timeout: 30_000 }); else await check(page.locator('.editor-section [role="alert"]')).toBeVisible({ timeout: 30_000 }); await submit().click(); await check(page.getByRole('alert').first()).toBeVisible(); expect((await metrics()).mutations).toEqual([]); }
    await flags({ badPrepared: '' }); await enterEdit(); await file().setInputFiles({ name: 'bad.txt', mimeType: 'text/plain', buffer: Buffer.from('bad') }); await check(page.locator('.editor-section [role="alert"]')).toBeVisible(); await submit().click(); expect((await metrics()).mutations).toEqual([]); await page.getByRole('button', { name: 'Mevcut içeriği koru', exact: true }).click(); await send(); expect((await metrics()).mutations.at(-1)?.keys).toEqual(['category', 'description', 'id', 'links', 'tags', 'title']); report('before-read count/unpacked/PPTX/path/duplicate and archive/parser/encoded/manifest/output guards zero invalid writes edit invalid save restore regression', { guard, metrics: await metrics() });
  });
  it('rejects UI file-count and synthetic byte metadata guards before reading or mutation', async () => {
    await enterCreate();
    await page.locator('.editor-dropzone').evaluate(element => { const dataTransfer = new DataTransfer(); for (let i = 0; i < 301; i++) dataTransfer.items.add(new File(['x'], `${i}.html`)); element.dispatchEvent(new DragEvent('drop', { bubbles: true, cancelable: true, dataTransfer })); });
    await check(page.locator('.editor-section [role="alert"]')).toContainText('300'); await submit().click(); expect((await metrics()).mutations).toEqual([]); expect((await metrics()).prep).toBe(0);
    for (const [name, size, expected] of [['big.html', 26 * 1024 * 1024, '25 MB'], ['big.pptx', 9 * 1024 * 1024, '8 MB']] as const) {
      await file().evaluate((element, value) => { const input = element as HTMLInputElement; const file = new File(['x'], value.name); Object.defineProperty(file, 'size', { value: value.size }); const transfer = new DataTransfer(); transfer.items.add(file); input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true })); }, { name, size });
      await check(page.locator('.editor-section [role="alert"]')).toContainText(expected); await submit().click(); expect((await metrics()).mutations).toEqual([]);
    }
    await page.locator('#editor-cover-file').evaluate(element => { const input = element as HTMLInputElement; const file = new File(['x'], 'large.png', { type: 'image/png' }); Object.defineProperty(file, 'size', { value: 11 * 1024 * 1024 }); const transfer = new DataTransfer(); transfer.items.add(file); input.files = transfer.files; input.dispatchEvent(new Event('change', { bubbles: true })); });
    await check(page.getByRole('alert').last()).toContainText('10 MB'); expect((await metrics()).covers).toBe(0); expect((await metrics()).mutations).toEqual([]); report('actual UI 301 files plus deterministic synthetic 26MB HTML/9MB PPTX/11MB cover metadata before reads; actual compressed byte rejection supplemented by limit test', await metrics());
  });
  it('validates title description trimmed labels HTTPS credentials URL lengths count with linked focus summary and no invalid writes', async () => {
    await enterEdit(); await page.locator('#editor-title').fill(''); await page.locator('#editor-description').fill('x'.repeat(2001)); await page.locator('#editor-link-0-label').fill(' '); await page.locator('#editor-link-0-url').fill('https://user:pass@example.test'); await submit().click(); await check(page.locator('.editor-summary')).toBeFocused(); await check(page.locator('#editor-title')).toHaveAttribute('aria-invalid', 'true'); await page.locator('.editor-summary a').first().click(); await check(page.locator('#editor-title')).toBeFocused(); expect((await metrics()).mutations).toEqual([]);
    await page.locator('#editor-title').fill('x'.repeat(121)); await page.locator('#editor-description').fill('Açıklama'); await page.locator('#editor-link-0-label').fill('x'.repeat(101)); await page.locator('#editor-link-0-url').fill(`https://example.test/${'x'.repeat(1000)}`); await submit().click(); expect((await metrics()).mutations).toEqual([]); await check(page.locator('#editor-title-error')).toContainText('120'); await check(page.locator('#editor-link-0-label-error')).toContainText('100');
    for (const url of ['http://example.test', 'https://', 'javascript:alert(1)', '/relative', 'https://example.test/bad path']) { await page.locator('#editor-link-0-url').fill(url); await submit().click(); expect((await metrics()).mutations).toEqual([]); }
    await page.locator('#editor-title').fill('  Güncel başlık  '); await page.locator('#editor-link-0-label').fill('  Kaynak  '); await page.locator('#editor-link-0-url').fill(' https://example.test/valid '); await send(); expect((await metrics()).mutations.at(-1)?.title).toBe('Güncel başlık'); expect((await metrics()).mutations.at(-1)?.links).toEqual([{ label: 'Kaynak', url: 'https://example.test/valid' }]); report('shared limits plus HTTPS parser empty/title120/description2000/label100/URL1000 credential checks summary field focus trimming zero invalid writes', await metrics());
  });
  it('saves metadata links cover-only and same-kind replacement, owns pending transition and preserves unchanged content', async () => {
    await enterEdit('pending'); await check(page.locator('.editor-review')).toContainText('yeni bekleyen sunum kotası kullanmaz'); await page.locator('#editor-description').fill('Yalnızca bilgi'); await send(); let m = (await metrics()).mutations.at(-1)!; expect(m.keys).toEqual(['category', 'description', 'id', 'links', 'tags', 'title']); expect((await metrics()).chunks).toEqual([]);
    await control('reset'); await control('service'); await enterEdit('own'); await check(page.locator('.editor-review')).toContainText('yeni bir bekleyen'); await page.getByRole('button', { name: 'Varsayılan kapağa dön' }).click(); await send(); m = (await metrics()).mutations.at(-1)!; expect(m.keys).toEqual(['category', 'cover', 'coverSource', 'description', 'id', 'links', 'tags', 'title']); expect(m.coverSource).toBe('default'); expect((await metrics()).chunks).toEqual([]);
    await control('reset'); await control('service'); await enterEdit('own'); await page.locator('#editor-title').fill('Değişen sunum'); await prepare(); await send(); m = (await metrics()).mutations.at(-1)!; expect(m.replacementKeys).toEqual([ 'chunkCount', 'chunks', 'fileName', 'manifest', 'sizes']); expect(m.title).toBe('Değişen sunum'); expect(m.html).toContain('deck-only'); expect(m.helper).toBe(false); expect(m.coverSource).toBe('auto');
    await control('reset'); await control('service'); await enterEdit('own'); await file().setInputFiles({ name: 'different.pptx', mimeType: 'application/octet-stream', buffer: pptx }); await check(page.locator('.editor-section [role="alert"]')).toContainText('yalnızca'); const count = (await metrics()).mutations.length; await submit().click(); expect((await metrics()).mutations).toHaveLength(count); report('pending metadata unchanged cover/chunks quota retained published cover-only and same-kind replacement exact payload re-review cross-kind zero write', await metrics());
  });
  it('recovers quota network permission and thrown save errors preserving fields, synchronously locks duplicate submissions', async () => {
    await enterEdit(); await page.locator('#editor-title').fill('Korunan başlık');
    for (const scenario of ['quota', 'mutation', 'permission', 'throw']) {
      await flags({ pending: scenario === 'quota' ? 5 : 0, error: scenario === 'mutation' || scenario === 'permission' ? scenario : '', throws: scenario === 'throw' ? 'mutation' : '' }); await submit().click(); await check(page.locator('form > [role="alert"]')).toBeVisible(); await check(page.locator('#editor-title')).toHaveValue('Korunan başlık'); expect((await metrics()).completions).toEqual([]);
    }
    await flags({ pending: 0, error: '', throws: '', hold: 'mutation' }); const before = (await metrics()).mutations.length; await submit().evaluate(button => { (button as HTMLButtonElement).click(); (button as HTMLButtonElement).click(); }); await check(submit()).toBeDisabled(); expect((await metrics()).mutations).toHaveLength(before + 1); await check(page.locator('progress')).not.toHaveAttribute('value'); await flags({ hold: '' }); await control('release', 'mutation'); await check(page.getByText('Sunum onaya gönderildi.', { exact: true })).toBeVisible(); expect((await metrics()).completions).toHaveLength(1); report('quota/network/permission/throw retry preserve fields duplicate synchronous lock indeterminate actual saving', await metrics());
  });
  it('discards delayed metadata preparation cover and preview on UID admin route service content logout and unmount', async () => {
    await flags({ hold: 'read' }); await control('auth', 'member'); await control('edit', 'own'); await check(page.getByRole('status')).toContainText('yükleniyor'); await control('edit', 'pending'); await control('auth', 'member2'); await control('auth', 'admin'); await control('service'); await control('auth', 'unauthenticated'); await flags({ hold: '' }); await control('release', 'read'); await check(file()).toHaveCount(0); expect((await metrics()).chunks).toEqual([]);
    for (const change of ['service', 'content', 'logout', 'unmount']) {
      await control('mount', true); await enterCreate(); await flags({ hold: 'prep' }); await file().setInputFiles({ name: 'old.html', mimeType: 'text/html', buffer: Buffer.from(smallHtml) }); await check(page.locator('progress')).toBeVisible();
      if (change === 'logout') await control('auth', 'unauthenticated'); else if (change === 'unmount') await control('mount', false); else await control(change as 'service' | 'content');
      expect(await page.getByText('Sunum hazır', { exact: true }).count()).toBe(0); const prepSettled = (await metrics()).preparedSettled; await flags({ hold: '' }); await control('release', 'prep'); await check.poll(async () => (await metrics()).preparedSettled, { timeout: 30_000 }).toBe(prepSettled + 1);
      await check(page.locator('#editor-title')).toHaveCount(change === 'logout' || change === 'unmount' ? 0 : 1); if (change === 'service' || change === 'content') await check(page.locator('#editor-title')).toHaveValue('');
    }
    await control('mount', true); await enterEdit(); await flags({ hold: 'chunks' }); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); await check(page.locator('progress')).toBeVisible(); await control('edit', 'pending'); await flags({ hold: '' }); await control('release', 'chunks'); await check(page.locator('#editor-title')).toBeVisible(); await check(page.locator('.editor-preview')).toHaveCount(0);
    await flags({ hold: 'cover' }); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.locator('progress')).toBeVisible(); await control('auth', 'unauthenticated'); const coverSettled = (await metrics()).coverSettled; await flags({ hold: '' }); await control('release', 'cover'); await check.poll(async () => (await metrics()).coverSettled).toBe(coverSettled + 1); await check(file()).toHaveCount(0); expect((await metrics()).completions).toEqual([]); expect((await metrics()).mutations).toEqual([]); report('late metadata/preparation/cover/chunks discarded on auth UID/admin/id/service/content/unmount keyed layout cleanup', await metrics());
  });
  it('discards late file reads before pipeline and late sent mutations cannot complete or refresh a new session', async () => {
    await enterCreate();
    await page.evaluate(() => { const original = File.prototype.arrayBuffer; (window as unknown as { releaseRead: () => Promise<void> }).releaseRead = async () => {}; File.prototype.arrayBuffer = function () { return new Promise<ArrayBuffer>(resolve => { (window as unknown as { releaseRead: () => Promise<void> }).releaseRead = () => { File.prototype.arrayBuffer = original; return original.call(this).then(resolve); }; }); }; });
    await file().setInputFiles({ name: 'late.html', mimeType: 'text/html', buffer: Buffer.from(smallHtml) }); await check(page.locator('progress')).toBeVisible(); await control('auth', 'unauthenticated'); await page.evaluate(() => (window as unknown as { releaseRead: () => Promise<void> }).releaseRead()); expect((await metrics()).prep).toBe(0); await check(file()).toHaveCount(0);
    for (const change of ['logout', 'id', 'service', 'content', 'unmount']) {
      await control('mount', true); await enterEdit('pending'); await flags({ hold: 'mutation' }); const calls = (await metrics()).mutations.length; await submit().click(); await check(submit()).toBeDisabled(); expect((await metrics()).mutations).toHaveLength(calls + 1);
      if (change === 'logout') await control('auth', 'unauthenticated'); else if (change === 'id') await control('edit', 'own'); else if (change === 'unmount') await control('mount', false); else await control(change as 'service' | 'content');
      const reads = (await metrics()).reads.length; const settled = (await metrics()).settled; await flags({ hold: '' }); await control('release', 'mutation'); await check.poll(async () => (await metrics()).settled).toBe(settled + 1); expect((await metrics()).completions).toEqual([]); expect((await metrics()).reads).toHaveLength(reads); expect((await metrics()).mutations).toHaveLength(calls + 1);
    }
    report('late file read no preparation plus already-sent mutation auth/id/service/content/unmount no callback/navigation/new write/refresh', await metrics());
  });
  it('limits resource count to ten and accepts removal then validates links-only and uploaded cover-only edits', async () => {
    await enterEdit('pending'); for (let index = 1; index < 10; index++) { await page.getByRole('button', { name: 'Bağlantı ekle', exact: true }).click(); await page.locator(`#editor-link-${index}-label`).fill(`Kaynak ${index + 1}`); await page.locator(`#editor-link-${index}-url`).fill(`https://example.test/${index}`); } await check(page.getByRole('button', { name: 'Bağlantı ekle', exact: true })).toBeDisabled(); await page.getByRole('button', { name: 'Bağlantı 10 kaldır' }).click(); await send(); expect((await metrics()).mutations.at(-1)?.keys).toEqual(['category', 'description', 'id', 'links', 'tags', 'title']); expect((await metrics()).mutations.at(-1)?.links).toHaveLength(9);
    await control('reset'); await control('service'); await enterEdit('pending'); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByText('Yüklediğiniz kapak', { exact: true })).toBeVisible(); await send(); expect((await metrics()).mutations.at(-1)?.coverSource).toBe('upload'); expect((await metrics()).mutations.at(-1)?.keys).toEqual(['category', 'cover', 'coverSource', 'description', 'id', 'links', 'tags', 'title']); expect((await metrics()).chunks).toEqual([]); report('ten resource maximum removal links-only uploaded processed-cover-only without original chunk reads', await metrics());
  });
  it('renders 20 actual responsive theme screenshots, one main, accessible keyboard focus reduced motion and long text without overflow', async () => {
    for (const theme of ['light', 'dark'] as const) for (const width of [375, 1280]) {
      await page.setViewportSize({ width, height: 900 }); await control('theme', theme); await check(page.locator('html')).toHaveAttribute('data-theme', theme); await check(page.locator('#theme-label')).toHaveText(`Tema: ${theme}`); if (await page.locator('.vektor-theme-controls:not([open])').count()) await page.getByLabel('Tema seçenekleri').click(); await check(page.getByRole('button', { name: theme === 'light' ? 'Koyu temaya geç' : 'Açık temaya geç', exact: true })).toBeVisible();
      await enterCreate(); await shot(`create-${width}-${theme}`);
      await enterEdit('own'); await check(page.locator('#editor-title')).toHaveValue('Mevcut Sunum'); await shot(`edit-${width}-${theme}`);
      await enterCreate(); await prepare(); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); await check(page.locator('.editor-preview iframe')).toBeVisible(); await shot(`html-preview-${width}-${theme}`);
      await enterCreate(); await prepare('sunum.pptx', pptx, 'application/octet-stream'); await page.getByRole('button', { name: 'Sunumu önizle', exact: true }).click(); await check(page.locator('.editor-pptx')).toBeVisible(); await shot(`pptx-${width}-${theme}`);
      await enterEdit('pending'); await page.locator('#editor-title').fill(''); await submit().click(); await check(page.locator('.editor-summary')).toBeFocused(); await shot(`error-${width}-${theme}`); await check(page.getByRole('main')).toHaveCount(1);
      await page.locator('.editor-summary a').first().click(); await check(page.locator('#editor-title')).toBeFocused(); await page.keyboard.press('Tab'); await check(page.locator('#editor-description')).toBeFocused(); const focus = await page.locator('#editor-description').evaluate(element => ({ outline: getComputedStyle(element).outlineWidth, motion: getComputedStyle(element).transitionDuration })); expect(focus.outline).toBe('3px'); expect(focus.motion).toBe('0s');
      await page.locator('#editor-title').fill('Ç'.repeat(120)); await page.locator('#editor-description').fill('UzunAçıklama'.repeat(170)); await page.locator('#editor-link-0-label').fill('K'.repeat(100)); await page.locator('#editor-link-0-url').fill(`https://example.test/${'x'.repeat(900)}`); await page.locator('#editor-description').blur(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true); await check(page.getByRole('button', { name: 'Vazgeç', exact: true })).toBeVisible();
    }
    expect(shots).toHaveLength(20); report('20 screenshots create/edit/HTML/PPTX/error at375/1280 actual ThemeProvider light/dark label+dataset single main keyboard summary/field focus rings reduced motion long text no overflow', { shots });
  });
  it('shows unresolved HTTPS warnings as text and auto-cover reset after uploaded override', async () => {
    await enterCreate(); const html = '<html><head><title>Dış kaynak</title><link rel="stylesheet" href="https://example.test/assets.css"></head><body style="background:white;color:black">Dış kaynak</body></html>';
    await prepare('external.html', Buffer.from(html)); await check(page.locator('.editor-warnings')).toContainText('https://example.test/assets.css'); await check(page.locator('.editor-warnings li')).toHaveCount(1); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByText('Yüklediğiniz kapak', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Otomatik kapağı kullan', exact: true }).click(); await check(page.getByText('Sunumdan otomatik yakalanan kapak', { exact: true })).toBeVisible(); await send(); expect((await metrics()).mutations.at(-1)?.coverSource).toBe('auto'); report('unresolved HTTPS warning target visibly rendered as text real auto/upload/reset cover selection', await metrics());
  });
  it('replaces PPTX with real identity payload, restores original cover and retains pending quota at maximum', async () => {
    await enterEdit('pptx'); await prepare('replacement.pptx', pptx, 'application/octet-stream'); await send(); let mutation = (await metrics()).mutations.at(-1)!; expect(mutation.fileName).toBe('replacement.pptx'); expect(mutation.replacementKeys).toEqual([ 'chunkCount', 'chunks', 'fileName', 'manifest', 'sizes']); expect(mutation.coverSource).toBe('default');
    const identity = await page.evaluate(() => { const input = window.editorInputs.at(-1)!; if (!('replacementContent' in input) || !input.replacementContent) return []; const content = input.replacementContent; const result = window.editorContent.reconstructPresentation(content.chunks, content.manifest, 'pptx', content.sizes); return result.ok ? Array.from(result.value.rawBytes) : []; }); expect(Buffer.from(identity)).toEqual(pptx); expect((await metrics()).completionStatuses).toEqual(['pending']);
    await control('reset'); await control('service'); await flags({ pending: 5 }); await enterEdit('pending'); await page.locator('#editor-cover-file').setInputFiles({ name: 'cover.png', mimeType: 'image/png', buffer: raster }); await check(page.getByText('Yüklediğiniz kapak', { exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Mevcut kapağı koru', exact: true }).click(); await check(page.getByText('Varsayılan kapak', { exact: true })).toBeVisible(); await send(); mutation = (await metrics()).mutations.at(-1)!; expect(mutation.keys).toEqual(['category', 'description', 'id', 'links', 'tags', 'title']); expect(await page.evaluate(() => { const input = window.editorInputs.at(-1)!; return 'replacementContent' in input; })).toBe(false); expect((await metrics()).completionStatuses).toEqual(['pending', 'pending']); report('actual same-kind PPTX replacement identity/default cover and original cover restore omit payload pending->pending succeeds at max5 quota', await metrics());
  });
  it('route adapters default close to my decks and success to internal encoded deck route', async () => {
    await control('navigate', '/yeni'); await control('auth', 'member'); await check(page.getByRole('heading', { name: 'Yeni Sunum Yükle', exact: true })).toBeVisible(); await page.getByRole('button', { name: 'Geri dön', exact: true }).click(); await check(page).toHaveURL(`${base}/benim`);
    await control('navigate', '/yeni'); await prepare(); await submit().click(); await check(page).toHaveURL(`${base}/s/created-1`);
    await control('navigate', '/duzenle/own'); await check(page.getByRole('heading', { name: 'Sunumu Düzenle', exact: true })).toBeVisible(); await submit().click(); await check(page).toHaveURL(`${base}/s/own`); report('typed /yeni /duzenle/:id Router/AppLayout default internal close and completion navigation; integration root untouched');
  });
});
